package leetcode.problems;

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
*/
class FindTheDifference {
    // Runtime: 2 ms, faster than 72.86% 
    public char findTheDifference(String s, String t) {
        int result = 0;
        
        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i);
        }
        
        for (int i = 0; i < t.length(); i++) {
            result ^= t.charAt(i);
        }
        
        return (char) result;
    }
}
